---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: rw-test-clusterrole
rules:
- apiGroups: [""]
  resources: [""]
  verbs: [ get, list, create, update, delete, deletecollection, watch ]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rw-test-sa
  namespace: resource-watcher-testnamespace
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: rw-test-sa
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rw-test-clusterrole
subjects:
- kind: ServiceAccount
  name: rw-test-sa
  namespace: resource-watcher-testnamespace
---
